function New-EalaWorkspace {
	<#
	.SYNOPSIS
		Creates a Log Analytics workspace.

	.DESCRIPTION
		Creates a Log Analytics workspace with optional tags, identity, retention, SKU, feature flags, replication, and custom properties.

	.PARAMETER Subscription
		The name or ID of the target Azure subscription.

	.PARAMETER ResourceGroup
		The name of the resource group in which to create the workspace.

	.PARAMETER Name
		The name of the Log Analytics workspace to create.

	.PARAMETER Location
		The Azure region in which to create the workspace.
		Defaults to: Location of the Resource Group

	.PARAMETER Etag
		An entity tag used for optimistic concurrency control.

	.PARAMETER Tags
		A hashtable of tags to assign to the workspace.

	.PARAMETER SystemIdentity
		Enables a system-assigned managed identity on the workspace.

	.PARAMETER RetentionDays
		The workspace data retention period in days.
		The minimum value is 4.

	.PARAMETER Sku
		The pricing SKU to assign to the workspace.

	.PARAMETER Features
		One or more WorkspaceFeatures flags to enable.

	.PARAMETER ReplicationLocation
		The secondary Azure region in which to enable workspace replication.

	.PARAMETER Properties
		A hashtable of additional workspace properties. These values override properties generated by the command.

	.PARAMETER WhatIf
		If this switch is enabled, no actions are performed but informational messages will be displayed that explain what would happen if the command were to run.

	.PARAMETER Confirm
		If this switch is enabled, you will be prompted for confirmation before executing any operations that change state.

	.PARAMETER ServiceMap
		Optional hashtable to map service names to specific EntraAuth service instances.
		Used for advanced scenarios where you want to use something other than the default Azure connection.
		Example: @{ Azure = 'MyAzure' }
		This will switch all Azure API calls to use the configuration defined in MyAzure.
		Defaults to: @{}

	.EXAMPLE
		PS C:\> New-EalaWorkspace -Subscription 'Production' -ResourceGroup 'rg-monitoring' -Name 'law-prod' -Location 'eastus' -Sku 'PerGB2018' -RetentionDays 90 -Features DisableLocalAuth

		Creates a workspace with 90-day retention and local authentication disabled.
	#>
	[CmdletBinding(SupportsShouldProcess = $true)]
	param (
		[Parameter(Mandatory = $true)]
		[PsfArgumentCompleter('EntraAuth.Azure.Subscription')]
		[string]
		$Subscription,

		[Parameter(Mandatory = $true)]
		[PsfArgumentCompleter('EntraAuth.Azure.ResourceGroup')]
		[string]
		$ResourceGroup,

		[Parameter(Mandatory = $true)]
		[PsfValidatePattern('^[A-Za-z0-9][A-Za-z0-9-]{2,61}[A-Za-z0-9]$', ErrorMessage = 'Invalid Name: {0}. Workspace names must be 4-63 characters long and only contain regular letters, numbers, and dashes.')]
		[string]
		$Name,

		[PsfArgumentCompleter('EntraAuth.Azure.Location')]
		[string]
		$Location,

		[string]
		$Etag,

		[hashtable]
		$Tags,

		[switch]
		$SystemIdentity,

		[Alias('retentionInDays')]
		[int]
		$RetentionDays,

		[PsfArgumentCompleter('EntraAuth.Azure.LogAnalytics.Sku')]
		[string]
		$Sku,

		[WorkspaceFeatures]
		$Features,

		[string]
		$ReplicationLocation,

		[hashtable]
		$Properties,

		[ServiceTransformAttribute()]
		[hashtable]
		$ServiceMap = @{}
	)
	begin {
		$services = $script:_serviceSelector.GetServiceMap($ServiceMap)
		Assert-EntraConnection -Cmdlet $PSCmdlet -Service $services.Azure
		$subscriptionID = Resolve-Subscription -Name $Subscription -Services $services -Cmdlet $PSCmdlet
	}
	process {
		$actualLocation = $Location
		if (-not $actualLocation) {
			$actualLocation = (Get-EaaResourceGroup -ServiceMap $services -Subscription $subscriptionID -Name $ResourceGroup).Location
		}

		$body = @{
			location = $actualLocation
		}
		if ($Etag) { $body.etag = $Etag }
		if ($SystemIdentity) {
			$body.identity = @{
				tenantId = (Get-EntraToken -Service $services.Azure).TenantId
				type     = 'SystemAssigned'
			}
		}
		if ($Tags) { $body.tags = $Tags }

		$propertySet = @{}
		foreach ($key in $Properties.Keys) {
			$propertySet[$key] = $Properties[$key]
		}
		if ($PSBoundParameters.Keys -contains 'RetentionDays') { $propertySet['retentionInDays'] = $RetentionDays }
		if ($PSBoundParameters.Keys -contains 'Sku') { $propertySet['sku'] = @{ name = $Sku } }
		if ($PSBoundParameters.Keys -contains 'Features') {
			$propertySet['features'] = @{ }
			if ($Features -band [WorkspaceFeatures]::DataAuthorizationMode) { $propertySet['features']['dataAuthorizationMode'] = $true }
			if ($Features -band [WorkspaceFeatures]::DisableLocalAuth) { $propertySet['features']['disableLocalAuth'] = $true }
			if ($Features -band [WorkspaceFeatures]::EnableDataExport) { $propertySet['features']['enableDataExport'] = $true }
			if ($Features -band [WorkspaceFeatures]::OnlyResourceAccess) { $propertySet['features']['enableLogAccessUsingOnlyResourcePermissions'] = $true }
			if ($Features -band [WorkspaceFeatures]::ImmediateDataPurge) { $propertySet['features']['immediatePurgeDataOn30Days'] = $true }
		}
		if ($ReplicationLocation) {
			$propertySet.replication = @{
				enabled  = $true
				location = $ReplicationLocation
			}
		}
		$body.properties = $propertySet

		Invoke-PSFProtectedCommand -Action "Creating Azure Log Analytics Workspace $Name in $SubscriptionID/$ResourceGroup" -Target $Name -ScriptBlock {
			Invoke-EntraRequest -Service $services.Azure -Method PUT -Path "subscriptions/$subscriptionID/resourcegroups/$ResourceGroup/providers/Microsoft.OperationalInsights/workspaces/$Name" -Query @{
				'api-version' = '2026-03-01'
			} -Body $body -ContentType 'application/json' | ConvertTo-Workspace
		} -EnableException $true -PSCmdlet $PSCmdlet
	}
}